name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add build and test steps here

  start-backend:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Start backend server
      run: |
        npm install
        node server.js &
      working-directory: .

  deploy:
    needs: start-backend
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Change this to your build directory
